version: 2.1

orbs:
  node: circleci/node@5

jobs:
  build-node:
    executor: node/default
    resource_class: small
    working_directory: ~/project/website

    steps:
      - checkout:
          path: ~/project

      - node/install-packages:
          pkg-manager: npm

      - run:
          name: Build Aether website
          command: npm run build

      - store_artifacts:
          path: dist
          destination: aether-site

workflows:
  build:
    jobs:
      - build-node
